osx_image: xcode8.3

sudo: required
dist: trusty

language: node_js
node_js:
  - "7"
install:
  - yarn install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
script:
  - yarn test
  - yarn dist-travis
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.electron
    - $HOME/.cache

matrix:
    include:
        - os: osx
        - os: linux
