image: Visual Studio 2017

branches:
  only:
  - master
  - pre-release

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
  - yarn install

build_script:
  - yarn dist

test: off
