image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
  - yarn install

build_script:
  - yarn dist-win

test: off

deploy:
    description: 'New windows release'
    provider: Github
    auth_token:
        secure: LpmAbg3e3SvnGegFlPZzOYrdFewjbk+LwroV7oCEqvaLJyqUm1qqW7cyFWVlJrGk
    prerelease: true
    on:
        branch: automatic_build
